theme: jekyll-theme-architect
title: Enhancing security in a blockchain ecosystem
description: >- # This is a multi-line description. The '>' means it will be parsed as a single string.
  Welcome to my professional portfolio! Here you'll find my essays,
  Analysing security challenges, propose improvements, and fortify systems against possible threats
