theme: jekyll-theme-architect
title: Enhancing security in a blockchain ecosystem
description: >-
  Welcome to my professional portfolio! Here you'll find my essays,
  Analysing security challenges, propose improvements, and fortify systems against possible threats.
